name: Deploy to WordPress.org
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          extensions: intl, mbstring, json, bcmath
          coverage: xdebug
          tools: composer:v1

      - name: Build
        run: |
          composer install --no-dev
          npm install
          gulp js:build
          gulp css:build
          rm -rf ./node_modules
          rm -rf ./tests
          rm -rf ./.git
          rm -rf ./vendor/swedbank-pay/swedbank-pay-sdk-php/.git
          rm -rf ./vendor/swedbank-pay/swedbank-pay-woocommerce-core/.git
          rm -rf ./.github
          rm -f ./package-lock.json
          rm -rf ./vendor/bin
          rm -rf ./vendor/squizlabs/php_codesniffer
          composer dump-autoload -o
          rm -f ./composer.lock

      - name: WordPress Plugin Deploy
        uses: varunsridharan/action-wp-org-deploy@main
        with:
          WORDPRESS_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          WORDPRESS_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: swedbank-pay-payments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
