name: Integration tests

on: [push, pull_request, pull_request_target]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    if: |
        (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
        (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request_target' }}
        with:
          path: swedbank-pay-woocommerce-payments

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          path: swedbank-pay-woocommerce-payments
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          extensions: intl, mbstring, json, bcmath
          coverage: xdebug
          tools: composer:v1

      - name: Run PHPCS inspection
        run: |
          cd $GITHUB_WORKSPACE/swedbank-pay-woocommerce-payments
          composer install
          ./vendor/bin/phpcs --standard=WordPress-Core --report=code --ignore=tests,docs,.github,assets,vendor --runtime-set ignore_warnings_on_exit true ./ || true

